### ISSUE TITLE
Client only sends to the first server

### ISSUE THREAD

**Issue by mo8it** [fcoury/yprox#5]
The following video shows that the second server doesn't receive anything.
This bug is introduced in this commit: https://github.com/fcoury/yprox/commit/f39de47c5e55a743ca21b984490c3d3540fb18bf
I am aware that only the reply of the first server is sent back to the client. But the other servers should at least receive.

[Screencast from 2023-11-12 22-32-30.webm](https://github.com/fcoury/yprox/assets/76752051/56ef9c4f-b318-4b8c-8f82-5db05f2d40c9)

**Comment by fcoury** [comment]
Thank you so much for taking the time to help me out. 

I noticed the same bug and I am reimplementing the core using just the standard library. I will push a draft of what I have in mind but would love to get your feedback if you have time.

**Comment by fcoury** [comment]
@mo8it here's a very early sketch of what I am planning on doing:

https://github.com/fcoury/testp/blob/master/src/main.rs

Let me know your thoughts

**Comment by mo8it** [comment]
This is funny because I am currently also inspecting the usage of a broadcaster to fix this (just out of interest).
Tokio offers a broadcast channel, but it has a hard upper limit which means that some servers might not receive everything if they lag behind. This is not optimal. I am currently looking at other libraries and then I will take a look at your manual approach :D

**Comment by mo8it** [comment]
You got me nerd sniped, but it is too late for me. I will check it out tomorrow if I find some time when I am back home :D

**Comment by fcoury** [comment]
I am excited @mo8it that you're sniped, being alone in those projects is never too much fun, now is it? :-)

I got my manual prototype working, check it out below. Also pushed the latest changes to the testp repo.

Basically I am running two nc in listener mode: ports 6001 and 6002. Then I am running the yprox server on port 6000 and multiplexing to 6001 and 6002 and taking also getting replies from the sockets and sending them back to the yprox server. 

Seems to be working, but I am sure the code is very sub-optimal as it stands:

https://github.com/fcoury/yprox/assets/1371/8acfa9e2-6b70-43e1-be7a-ff126608af45

**Comment by fcoury** [comment]
Hey @mo8it closing this since I think the rewrite took care of this bug. Feel free to reopen if you find this wasn't the case 😊
